#!/bin/sh

duration=5

while getopts "d:" opt
do
   case "$opt" in
      d ) duration="$OPTARG" ;;
      ? ) exit 0 ;;
   esac
done

while true
	do 
		clear
		ls /usr/share/cowsay | grep ".cow" | sort -R | tail -n 1 | while read file
		do 
			cowsay -f $file $(fortune)
			echo "file: $file"
		done
	sleep $duration
done
