#!/bin/sh

echo -n "User for Diskstation:"
read username

if [ -z $username ]
then
    username="$USER"
    echo "No username provided using: $username"
fi

echo -n "Password for Diskstation:"
read -s password
echo

mount //Diskstation/Tobias /mnt/Diskstation/Tobias -o username=$username,vers=1.0,pass=$password
mount //Diskstation/Music  /mnt/Diskstation/Music -o username=$username,vers=1.0,pass=$password

echo "done"
