#!/bin/sh

while getopts "u:p:" opt
do
   case "$opt" in
      u ) username="$OPTARG" ;;
      p ) password="$OPTARG" ;;
   esac
done

if [ -z $username ]
then
   echo -n "User for Diskstation:"
   read username

   if [ -z $username ]
   then
      username="$USER"
      echo "No username provided using: $username"
   fi
fi

if [ -z $password ] 
then
   echo -n "Password for Diskstation:"
   read -s password
   echo
fi

mount -t nfs 192.168.178.26:/volume1/Tobias /mnt/Diskstation/Tobias
mount //Diskstation/Music  /mnt/Diskstation/Music -o user=$username,pass=$password,file_mode=0777,dir_mode=0777

echo "done"
