#!/bin/sh

rename_file() {
    line=$(head -n 1 "$1")
    if [ "${line:0:2}" == "# " ]; then
        title=${line:2}
        filename=$(basename "$1")
        if [ "$title.md" != "$filename" ]; then
            dir=$(dirname "$1")
            mv "$1" "$dir/$title.md"
        fi
    fi
}

if [ -f "$1" ]; then
    $EDITOR "$1" -c AutoSaveToggle
    rename_file "$1"
else
    dirname=$(dirname $1)
    date=$(date)
    date=${date:0:10}
    name="$date $(basename $1)"
    
    for a in "${@:2}"; do
        name="$name $a"
    done
    
    filename="$dirname/$name.md"
    
    echo "# $name" >> "$filename"
    $EDITOR "$filename" -c AutoSaveToggle
    rename_file "$filename"
fi
