#!/bin/sh

rename_file() {
    line=$(head -n 1 "$1")
    if [ "${line:0:2}" == "# " ]; then
        title=${line:2}
        filename=$(basename "$1")
        if [ "$title.md" != "$filename" ]; then
            dir=$(dirname "$1")
            mv "$1" "$dir/$title.md"
        fi
    fi
}

if [ -f "$1" ]; then
    filename="$1"
else
    dirname=$(dirname $1)
    basename=$(basename $1)

    if [ "$basename" == "_" ]; then
        for f in $dirname/*; do
            filename="$f"
        done
    else
        date=$(date)
        date=${date:0:10}
        name="$date $basename"
        
        for a in "${@:2}"; do
            name="$name $a"
        done
        
        filename="$dirname/$name.md"
        echo "# $name" >> "$filename"
    fi
fi

$EDITOR "$filename" -c AutoSaveToggle
rename_file "$filename"
