#!/bin/sh

if [[ "$1" == "-b" ]] || [[ "$1" == "--bare" ]]; then
    shift
    /usr/bin/git --git-dir=/usr/local/bin/.scripts/ "$@"
else
    /usr/bin/git --git-dir=/usr/local/bin/.scripts/ --work-tree=/usr/local/bin/ "$@"
fi
